### ISSUE TITLE
Balloon pops without code 

### ISSUE THREAD

**Issue by brijrajsingh** [raspberrypilearning/balloon-pi-tay-popper#10]
Please see my attached diagram, I am using your code and identical connections, the "pop" msg printing with tactile switch works just fine, but when i do the full implementation, i find that the balloon pops the moment i input the battery.
I later started checking with LED, there is no effect over the LED, neither it gets hot or turns off by the code given, the code doesn't show any error as well

I however see this warning in my console

balloon_updated.py:13: RuntimeWarning: A physical pull up resistor is fitted on this channel!
  GPIO.setup(balloon, GPIO.OUT)
![img_0151](https://cloud.githubusercontent.com/assets/1260127/10869501/f604d5cc-80d7-11e5-99b0-980afac0f252.JPG)
![img_0152](https://cloud.githubusercontent.com/assets/1260127/10869502/f70aac4e-80d7-11e5-8402-0bb5a278b777.JPG)
![img_0153](https://cloud.githubusercontent.com/assets/1260127/10869503/f8c6d8c8-80d7-11e5-88d9-0d65918b9781.JPG)

**Comment by juggledad** [comment]
Make sure you transistor is in the correct way. Some transistors have the EBC in a different order.

**Comment by brijrajsingh** [comment]
Should I just revert it in such a case, So if its the other way around it should work, I just hope I don't end up burning my pi.

**Comment by juggledad** [comment]
You need to look at the data sheet for the transistor from the company that makes it (google it) to see the correct layout.

**Comment by brijrajsingh** [comment]
yes, Found that my transistor had order EBC unlike yours, the code works like a charm
