### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/balloon-pi-tay-popper#11]
Hi @lauraclay / @LornaLynch 
Could I get a copy edit on this update please:
New fork is at - https://github.com/raspberrypilearning/balloon-pi-tay-popper/tree/gpiozero-update
Comparison of new and original at - https://github.com/raspberrypilearning/balloon-pi-tay-popper/compare/gpiozero-update?expand=1

I've changed some diagrams and updated the copy and code for gpiozero
Not too many changes

Thanks

**Comment by LornaLynch** [comment]
Is it a problem that, in the section where the speaker cable/resistor circuit is being prepared, there's no red or black electrical tape on the cables, though this is mentioned in the worksheet?

**Comment by MarcScott** [comment]
It's not a massive issue. I'll take some new photos when I'm back in the office. Good spot though.

**Comment by LornaLynch** [comment]
Final one from me, and then the edit is done: I'd say the interactive calculator suggestion in what next might need a tiny bit of explanation? Is there something that could be linked to?

**Comment by LornaLynch** [comment]
Other than this I'd say you're ok to close this issue.

**Comment by MarcScott** [comment]
Thanks @LornaLynch

**Comment by MarcScott** [comment]
@davidhoness was this your resource originally? Could you clarify the interactive calculator suggestion at the end.

**Comment by bennuttall** [comment]
It was an external one, rewritten by me & Rachel. I'll take a look.

**Comment by lauraclay** [comment]
Reopening, as I've spotted some further edits are needed. (Apologies for just seeing this- problems migrating my email meant I've missed a week of notifications!)

**Comment by LornaLynch** [comment]
Apologies @lauraclay :(
