### ISSUE TITLE
Should it be GPIO2 or GPIO pin 2

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/balloon-pi-tay-popper#20]
I think the resource should state GPIO2, GPIO3 and GPIO14, not GPIO pin 2 etc.
To me, GPIO pin 2 refers to the physical pin, not the BCM pin number.

**Comment by lawsie** [comment]
I've altered it in your commit!

**Comment by SteveAmor** [comment]
Shall I raise a PR to change all `GPIO pin X` to `GPIO X` in the worksheet?

**Comment by lawsie** [comment]
If you have time, that would be great :) Thanks.
